"""Write crates/pipeline/src/tone_adobe.rs from the oracle ramps (t2)."""
import numpy as np, os, tables
base, T = tables.load()
# deep-shadow ends: where Camera Raw clipped to black there is no measurement; hold the nearest value
def clean(a):
    a = np.array(a, float); a[~np.isfinite(a)] = 0.0; return np.clip(a, -8, 8)
f = lambda a: "[" + ", ".join(f"{v:.4f}" for v in clean(a)) + "]"
key_ramp = float(np.mean(np.clip(np.linspace(-14, 0.5, 1024) - np.log2(0.18), -14, 10)))
out = ["//! Lightroom's (Camera Raw's) PV2012 Basic tone over an Adobe base, measured with Camera Raw itself",
       "//! (Bryan's fork, `docs/lr-match.md` → Round 4): synthetic DNGs with known settings rendered by",
       "//! Camera Raw in Photoshop, compared with the ACR3 base curve. Generated by",
       "//! `tools/lr-compare` oracle `gen_tables.py`; do not edit by hand.",
       "//!",
       "//! Every table is an EV shift on a grid of input EV (relative to middle grey) from [`EV0`] in steps",
       "//! of [`STEP`]: `BASE` at zero sliders, then per slider the shift at each measured slider value",
       "//! (relative to `BASE`; between measured values linear, 0 at 0).",
       "#![allow(clippy::approx_constant)] // measured numbers that happen to be near π/8",
       f"pub const EV0: f32 = {tables.G[0]:.2f};", f"pub const STEP: f32 = {tables.G[1]-tables.G[0]:.2f};", f"pub const N: usize = {len(tables.G)};",
       f"/// The key ([`super::lr::image_key`]) of the measurement ramp: Contrast's pivot moves with the",
       f"/// photo's key by [`CONTRAST_PIVOT`] EV per EV from it.",
       f"pub const KEY_RAMP: f32 = {key_ramp:.4f};", "pub const CONTRAST_PIVOT: f32 = 0.21;",
       f"pub const BASE: [f32; N] = {f(base)};"]
for k in ["E", "C", "W", "K"]:
    vs = sorted(T[k])
    out.append(f"pub const {k}_VALUES: [f32; {len(vs)}] = [" + ", ".join(f"{v:.2f}" for v in vs) + "];")
    out.append(f"pub const {k}_TABLE: [[f32; N]; {len(vs)}] = [\n" + ",\n".join("    " + f(T[k][v]) for v in vs) + ",\n];")
open(os.path.expanduser("~/crafts/lightcraft/crates/pipeline/src/tone_adobe.rs"), "w").write("\n".join(out) + "\n")
print("ok", key_ramp)
